### ISSUE TITLE
Full liberation

### ISSUE THREAD

**Issue by throwaway1037** [mrDIMAS/StationIapetus#2]
Release all data (audio, models, graphics, etc...) under [libre](https://freedomdefined.org) licenses.

This would make Station Lapetus fully free (as in freedom) and able to be packaged for systems which only allow libre software and data like [Parabola](https://parabola.nu).

**Comment by throwaway1037** [comment]
Example sites with libre data:
https://publicdomaintextures.com
https://cc0textures.com

**Comment by throwaway1037** [comment]
Anyone there?

**Comment by mrDIMAS** [comment]
Hi! Sorry, I missed this issue. I'm not sure it is possible, I use my own savings for development and want to earn some money in Steam. Maybe the "liberation" will be possible after some time after release, but this is not 100%.

**Comment by throwaway1037** [comment]
You can make money with libre software and data; in fact, that's part of the [definition](https://freedomdefined.org) of libre media. It's free as in freedom, not free as in price.

Plus, liberation would have many practical benefits, like being able to package it for GNU+Linux-libre distributions which are 100% libre, like [Parabola](https://parabola.nu), people would be free to find and fix bugs in the data, and people would be free to improve the game by making their own data and sharing it back with the project.

**Comment by Lyamc** [comment]
Based on the very description of the Readme:

> 3rd person shooter in the very early development phase. This is commercial project that will eventually be released in Steam. Also, the project is meant to be the proof that [rg3d](https://github.com/mrDIMAS/rg3d) game engine is ready for commercial production.

This issue should be closed. If throwaway1037 is contributing assets, they can always submit a pull request. Someone can use their own assets if they care that much and “liberate” those.

**Comment by throwaway1037** [comment]
Commercial is not the same thing as proprietary.
Libre games can be commercial and sold just the same as proprietary games.
